## Regression for Scikit_learn

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


# other
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
# import dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [22]:
# simple linear regression model
# x feature always wil be in double brackets/ dimension
x = df[['age']]
y = df['fare']

In [23]:
# lets check for null values
x.isnull().sum() / len(x)  # checking null values in x

age    0.198653
dtype: float64

In [32]:
# before proceeding we have to handle null values
x ['age'] = x['age'].fillna(x['age'].mean(), inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_21796\1465095393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x ['age'] = x['age'].fillna(x['age'].mean(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_21796\1465095393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x ['age'] = x['age'].fillna(x['age'].mean(), inplace=True)

In [28]:
x

      age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [40]:
x.age.fillna(value=x['age'].mean())

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
886   NaN
887   NaN
888   NaN
889   NaN
890   NaN
Name: age, Length: 891, dtype: float64

In [ ]:
x.isnull().sum() / len(x) *100  # checking null values in x

age    100.0
dtype: float64